// Code generated by genffi. DO NOT EDIT.

package model  
        
type Status string
  
const (
  StatusACCEPTED Status = "ACCEPTED"
  StatusRUNNING Status = "RUNNING"
  StatusSUCCESSFUL Status = "SUCCESSFUL"
  StatusFAILED Status = "FAILED"
  StatusDISMISSED Status = "DISMISSED"
)
    
type ProgressOperation string
  
const (
  ProgressOperationADD ProgressOperation = "ADD"
  ProgressOperationSUBTRACT ProgressOperation = "SUBTRACT"
)
    