// Code generated by genffi. DO NOT EDIT.

package model  
        
type Status string
  
const (
  StatusACCEPTED Status = "ACCEPTED"
  StatusRUNNING Status = "RUNNING"
  StatusSUCCESSFUL Status = "SUCCESSFUL"
  StatusFAILED Status = "FAILED"
  StatusDISMISSED Status = "DISMISSED"
)
    
type ProgressOperation string
  
const (
  ProgressOperationADD ProgressOperation = "ADD"
  ProgressOperationSUBTRACT ProgressOperation = "SUBTRACT"
)
    
type Result string
  
const (
  ResultSUCCESS Result = "SUCCESS"
  ResultFAILURE Result = "FAILURE"
  ResultRETRY Result = "RETRY"
  ResultONHOLD Result = "ONHOLD"
)
    
type Queue string
  
const (
  QueueLOCAL Queue = "LOCAL"
  QueueREDIS Queue = "REDIS"
)
    