// Code generated by genffi. DO NOT EDIT.

package model

type InitProgress struct {
  Total int `json:"total"`
  Details map[string]any `json:"details"`
}

func NewInitProgress(
  total int,
  details map[string]any,
) *InitProgress {

  return &InitProgress{
    Total: total,
    Details: details,
  }
}
  