// Code generated by genffi. DO NOT EDIT.

package model

type Job struct {
  BaseJob
  Label string `json:"label"`
  Description string `json:"description"`
  Inputs map[string]any `json:"inputs"`
  Outputs map[string]any `json:"outputs"`
  Setup *PartialJob `json:"setup"`
  Cleanup *PartialJob `json:"cleanup"`
  FollowUps []Job `json:"followUps"`
  Sequence *JobSequence `json:"sequence"`
}

func NewJob(
  id string,
  kind string,
  createdAt int64,
  startedAt int64,
  updatedAt int64,
  finishedAt int64,
  priority int,
  progress JobProgress,
  status Status,
  errors []string,
  context map[string]any,
  label string,
  description string,
  inputs map[string]any,
  outputs map[string]any,
  setup *PartialJob,
  cleanup *PartialJob,
  followUps []Job,
  sequence *JobSequence,
) *Job {

  return &Job{
    BaseJob: BaseJob{
      Id: id,
      Kind: kind,
      CreatedAt: createdAt,
      StartedAt: startedAt,
      UpdatedAt: updatedAt,
      FinishedAt: finishedAt,
      Priority: priority,
      Progress: progress,
      Status: status,
      Errors: errors,
      Context: context,
    },
    Label: label,
    Description: description,
    Inputs: inputs,
    Outputs: outputs,
    Setup: setup,
    Cleanup: cleanup,
    FollowUps: followUps,
    Sequence: sequence,
  }
}
  