// Code generated by genffi. DO NOT EDIT.

package model

type JobConfiguration struct {
  Kind string `json:"kind"`
  Priority int `json:"priority"`
  Label string `json:"label"`
  Description string `json:"description"`
  Inputs map[string]any `json:"inputs"`
  Context map[string]any `json:"context"`
  Progress JobProgress `json:"progress"`
  Setup bool `json:"setup"`
  Cleanup bool `json:"cleanup"`
  FollowUps []JobConfiguration `json:"followUps"`
}

func NewJobConfiguration(
  kind string,
  priority int,
  label string,
  description string,
  inputs map[string]any,
  context map[string]any,
  progress JobProgress,
  setup bool,
  cleanup bool,
  followUps []JobConfiguration,
) *JobConfiguration {

  return &JobConfiguration{
    Kind: kind,
    Priority: priority,
    Label: label,
    Description: description,
    Inputs: inputs,
    Context: context,
    Progress: progress,
    Setup: setup,
    Cleanup: cleanup,
    FollowUps: followUps,
  }
}
  