// Code generated by genffi. DO NOT EDIT.

package model

type JobProgress struct {
  Current int `json:"current"`
  Total int `json:"total"`
  Percent int `json:"percent"`
  Details map[string]any `json:"details"`
}

func NewJobProgress(
  current int,
  total int,
  percent int,
  details map[string]any,
) *JobProgress {

  return &JobProgress{
    Current: current,
    Total: total,
    Percent: percent,
    Details: details,
  }
}
  