// Code generated by genffi. DO NOT EDIT.

package model

type JobResult struct {
  Status Result `json:"status"`
  Messages []string `json:"messages"`
}

func NewJobResult(
  status Result,
  messages []string,
) *JobResult {

  return &JobResult{
    Status: status,
    Messages: messages,
  }
}
  