// Code generated by genffi. DO NOT EDIT.

package model

type JobResult struct {
  Message string `json:"message"`
  Status Status `json:"status"`
  Errors []string `json:"errors"`
}

func NewJobResult(
  message string,
  status Status,
  errors []string,
) *JobResult {

  return &JobResult{
    Message: message,
    Status: status,
    Errors: errors,
  }
}
  