// Code generated by genffi. DO NOT EDIT.

package model

type JobSequence struct {
  Current int `json:"current"`
  Remaining int `json:"remaining"`
}

func NewJobSequence(
  current int,
  remaining int,
) *JobSequence {

  return &JobSequence{
    Current: current,
    Remaining: remaining,
  }
}
  