// Code generated by genffi. DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
)

// UnmarshalJobProgress decodes a JobProgress from its JSON representation.
func UnmarshalJobProgress(data []byte) (JobProgress, error) {
	var value JobProgress
	err := json.Unmarshal(data, &value)
	return value, err
}

// MarshalJobProgress encodes a JobProgress as JSON. It panics rather than returning an error:
// every field of a generated type is JSON-representable by construction, so a failure
// here is a bug in genffi and not a condition a caller can act on.
func MarshalJobProgress(value JobProgress) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshaling JobProgress: %v", err))
	}
	return data
}

// UnmarshalJobSequence decodes a JobSequence from its JSON representation.
func UnmarshalJobSequence(data []byte) (JobSequence, error) {
	var value JobSequence
	err := json.Unmarshal(data, &value)
	return value, err
}

// MarshalJobSequence encodes a JobSequence as JSON. It panics rather than returning an error:
// every field of a generated type is JSON-representable by construction, so a failure
// here is a bug in genffi and not a condition a caller can act on.
func MarshalJobSequence(value JobSequence) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshaling JobSequence: %v", err))
	}
	return data
}

// UnmarshalOutputValue decodes a OutputValue from its JSON representation.
func UnmarshalOutputValue(data []byte) (OutputValue, error) {
	var value OutputValue
	err := json.Unmarshal(data, &value)
	return value, err
}

// MarshalOutputValue encodes a OutputValue as JSON. It panics rather than returning an error:
// every field of a generated type is JSON-representable by construction, so a failure
// here is a bug in genffi and not a condition a caller can act on.
func MarshalOutputValue(value OutputValue) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshaling OutputValue: %v", err))
	}
	return data
}

// UnmarshalProgressUpdate decodes a ProgressUpdate from its JSON representation.
func UnmarshalProgressUpdate(data []byte) (ProgressUpdate, error) {
	var value ProgressUpdate
	err := json.Unmarshal(data, &value)
	return value, err
}

// MarshalProgressUpdate encodes a ProgressUpdate as JSON. It panics rather than returning an error:
// every field of a generated type is JSON-representable by construction, so a failure
// here is a bug in genffi and not a condition a caller can act on.
func MarshalProgressUpdate(value ProgressUpdate) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshaling ProgressUpdate: %v", err))
	}
	return data
}

// UnmarshalBaseJob decodes a BaseJob from its JSON representation.
func UnmarshalBaseJob(data []byte) (BaseJob, error) {
	var value BaseJob
	err := json.Unmarshal(data, &value)
	return value, err
}

// MarshalBaseJob encodes a BaseJob as JSON. It panics rather than returning an error:
// every field of a generated type is JSON-representable by construction, so a failure
// here is a bug in genffi and not a condition a caller can act on.
func MarshalBaseJob(value BaseJob) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshaling BaseJob: %v", err))
	}
	return data
}

// UnmarshalPartialJob decodes a PartialJob from its JSON representation.
func UnmarshalPartialJob(data []byte) (PartialJob, error) {
	var value PartialJob
	err := json.Unmarshal(data, &value)
	return value, err
}

// MarshalPartialJob encodes a PartialJob as JSON. It panics rather than returning an error:
// every field of a generated type is JSON-representable by construction, so a failure
// here is a bug in genffi and not a condition a caller can act on.
func MarshalPartialJob(value PartialJob) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshaling PartialJob: %v", err))
	}
	return data
}

// UnmarshalJob decodes a Job from its JSON representation.
func UnmarshalJob(data []byte) (Job, error) {
	var value Job
	err := json.Unmarshal(data, &value)
	return value, err
}

// MarshalJob encodes a Job as JSON. It panics rather than returning an error:
// every field of a generated type is JSON-representable by construction, so a failure
// here is a bug in genffi and not a condition a caller can act on.
func MarshalJob(value Job) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshaling Job: %v", err))
	}
	return data
}

// UnmarshalJobResult decodes a JobResult from its JSON representation.
func UnmarshalJobResult(data []byte) (JobResult, error) {
	var value JobResult
	err := json.Unmarshal(data, &value)
	return value, err
}

// MarshalJobResult encodes a JobResult as JSON. It panics rather than returning an error:
// every field of a generated type is JSON-representable by construction, so a failure
// here is a bug in genffi and not a condition a caller can act on.
func MarshalJobResult(value JobResult) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshaling JobResult: %v", err))
	}
	return data
}
