// Code generated by genffi. DO NOT EDIT.

package model

type OutputValue struct {
  Value any `json:"value"`
  Href string `json:"href"`
  Kind string `json:"kind"`
}

func NewOutputValue(
  value any,
  href string,
  kind string,
) *OutputValue {

  return &OutputValue{
    Value: value,
    Href: href,
    Kind: kind,
  }
}
  