// Code generated by genffi. DO NOT EDIT.

package model

type PartialJob struct {
  BaseJob
  PartOf string `json:"partOf"`
  Executor string `json:"executor"`
  OnHold bool `json:"onHold"`
  ProgressUpdates []ProgressUpdate `json:"progressUpdates"`
  Sequence *int `json:"sequence"`
}

func NewPartialJob(
  id string,
  kind string,
  createdAt int64,
  startedAt int64,
  updatedAt int64,
  finishedAt int64,
  priority int,
  progress JobProgress,
  status Status,
  errors []string,
  context map[string]any,
  partOf string,
  executor string,
  onHold bool,
  progressUpdates []ProgressUpdate,
  sequence *int,
) *PartialJob {

  return &PartialJob{
    BaseJob: BaseJob{
      Id: id,
      Kind: kind,
      CreatedAt: createdAt,
      StartedAt: startedAt,
      UpdatedAt: updatedAt,
      FinishedAt: finishedAt,
      Priority: priority,
      Progress: progress,
      Status: status,
      Errors: errors,
      Context: context,
    },
    PartOf: partOf,
    Executor: executor,
    OnHold: onHold,
    ProgressUpdates: progressUpdates,
    Sequence: sequence,
  }
}
  