// Code generated by genffi. DO NOT EDIT.

package model

type ProgressUpdate struct {
  Path string `json:"path"`
  Operation ProgressOperation `json:"operation"`
}

func NewProgressUpdate(
  path string,
  operation ProgressOperation,
) *ProgressUpdate {

  return &ProgressUpdate{
    Path: path,
    Operation: operation,
  }
}
  