// Code generated by genffi. DO NOT EDIT.

package model

type SetOutputs struct {
  Outputs map[string]any `json:"outputs"`
}

func NewSetOutputs(
  outputs map[string]any,
) *SetOutputs {

  return &SetOutputs{
    Outputs: outputs,
  }
}
  