// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs.internal;

/**
 * A {@code @listener}: implemented by you, called by the library.
 *
 * <p>A method returning {@code void} is <b>fire-and-forget</b> — the library posts the
 * invocation and carries on without waiting, so nothing you do there can be observed by the
 * caller, and taking a long time applies back-pressure rather than blocking it.
 *
 * <p>Calls arrive on a single daemon thread named {@code genffi-upcall}, so they are
 * delivered in the order the library made them and never overlap.
 *
 * <p>An exception thrown by a fire-and-forget method is caught and reported to
 * {@code System.err}; it cannot reach the library.
 *
 * <pre>{@code
 * try (var registration = JobListener.register(myImplementation)) {
 *   // pass registration wherever the api declares a JobListener parameter
 * }
 * }</pre>
 *
 * <p>Generated — do not edit.
 */
public interface JobListener {

  void onProgress(de.ii.xtralink.jobs.Job job);

  /**
   * Registers {@code implementation} with the library and returns the token holding its id.
   * Close the token when you are done; until you do, the library keeps delivering to it.
   */
  static Registration register(JobListener implementation) {
    return new Registration(Ffi.register$(implementation));
  }

  /** A live registration. Pass it where a {@code JobListener} parameter is declared. */
  final class Registration implements AutoCloseable {

    private final long id;
    private boolean closed;

    Registration(long id) {
      this.id = id;
    }

    long id() {
      return id;
    }

    /**
     * Stops delivery and releases the id. Idempotent.
     *
     * <p>Invocations the library has already posted may still arrive; ones it posts
     * afterwards are dropped. That is deliberate — a registration closing while the
     * implementation is mid-emit is an ordinary race, and there is nobody left to deliver
     * to.
     */
    @Override
    public void close() {
      if (closed) {
        return;
      }

      closed = true;
      Ffi.unregister$(id);
    }
  }
}
