// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs.internal;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

/**
 * A {@code @singleton}: one instance for the process, constructed by {@code InitLibrary}
 * when {@code Ffi} is first touched. Nothing to hold, hence static methods and no
 * constructor.
 *
 * <p>Generated — do not edit.
 */
public final class JobQueue {

  private JobQueue() {}

  public static void start(de.ii.xtralink.jobs.QueueConfiguration cfg) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment cerr$ = arena.allocate(Ffi.C_POINTER);
      byte[] cfg$json = Ffi.json$write(cfg);
      Ffi.JobQueue_Start$MH.invokeExact(Ffi.bytes(arena, cfg$json), cfg$json == null ? 0L : (long) cfg$json.length, cerr$);

      MemorySegment err$ = cerr$.get(Ffi.C_POINTER, 0);

      if (err$.address() != 0) {
        String message$ = Ffi.str(err$);
        Ffi.freeString(err$);
        throw new FfiException(message$);
      }
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static void stop() {
    try {
      Ffi.JobQueue_Stop$MH.invokeExact();
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static java.util.concurrent.CompletableFuture<de.ii.xtralink.jobs.Job> push(de.ii.xtralink.jobs.JobConfiguration job, JobListener.Registration onProgress) {
    final long future$;

    try (Arena arena = Arena.ofConfined()) {
      byte[] job$json = Ffi.json$write(job);
      long ret$ = (long) Ffi.JobQueue_Push_Start$MH.invokeExact(Ffi.bytes(arena, job$json), job$json == null ? 0L : (long) job$json.length, onProgress.id());

      future$ = ret$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }

    return Ffi.pending$(future$, () -> await$push(future$));
  }

  private static de.ii.xtralink.jobs.Job await$push(long future$) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment clen$ = arena.allocate(Ffi.C_SIZE_T);
      MemorySegment ret$ = (MemorySegment) Ffi.JobQueue_Push_Await$MH.invokeExact(future$, clen$);
      long len$ = clen$.get(Ffi.C_SIZE_T, 0);

      de.ii.xtralink.jobs.Job out$ = Ffi.json$read(ret$, len$, de.ii.xtralink.jobs.Job.class);
      Ffi.freeBytes(ret$);

      return out$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  /**
   * Registers {@code onProgress} and releases it again when
   * the returned future completes.
   *
   * <p>Available because the method is declared {@code @scoped}, which asserts that it does
   * not retain the listener beyond that point. Use the {@code Registration}
   * overload for a listener that has to outlive it.
   */
  public static java.util.concurrent.CompletableFuture<de.ii.xtralink.jobs.Job> push(de.ii.xtralink.jobs.JobConfiguration job, JobListener onProgress) {
    JobListener.Registration onProgress$reg = JobListener.register(onProgress);

    return push(job, onProgress$reg).whenComplete((result$, error$) -> { onProgress$reg.close(); });
  }

  public static java.util.concurrent.CompletableFuture<de.ii.xtralink.jobs.PartialJob> pushPartial(de.ii.xtralink.jobs.PartialJobConfiguration partialJob) {
    final long future$;

    try (Arena arena = Arena.ofConfined()) {
      byte[] partialJob$json = Ffi.json$write(partialJob);
      long ret$ = (long) Ffi.JobQueue_PushPartial_Start$MH.invokeExact(Ffi.bytes(arena, partialJob$json), partialJob$json == null ? 0L : (long) partialJob$json.length);

      future$ = ret$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }

    return Ffi.pending$(future$, () -> await$pushPartial(future$));
  }

  private static de.ii.xtralink.jobs.PartialJob await$pushPartial(long future$) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment clen$ = arena.allocate(Ffi.C_SIZE_T);
      MemorySegment ret$ = (MemorySegment) Ffi.JobQueue_PushPartial_Await$MH.invokeExact(future$, clen$);
      long len$ = clen$.get(Ffi.C_SIZE_T, 0);

      de.ii.xtralink.jobs.PartialJob out$ = Ffi.json$read(ret$, len$, de.ii.xtralink.jobs.PartialJob.class);
      Ffi.freeBytes(ret$);

      return out$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static java.util.concurrent.CompletableFuture<de.ii.xtralink.jobs.PartialJob> repushPartial(String id) {
    final long future$;

    try (Arena arena = Arena.ofConfined()) {
      long ret$ = (long) Ffi.JobQueue_RepushPartial_Start$MH.invokeExact(Ffi.str(arena, id));

      future$ = ret$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }

    return Ffi.pending$(future$, () -> await$repushPartial(future$));
  }

  private static de.ii.xtralink.jobs.PartialJob await$repushPartial(long future$) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment clen$ = arena.allocate(Ffi.C_SIZE_T);
      MemorySegment ret$ = (MemorySegment) Ffi.JobQueue_RepushPartial_Await$MH.invokeExact(future$, clen$);
      long len$ = clen$.get(Ffi.C_SIZE_T, 0);

      de.ii.xtralink.jobs.PartialJob out$ = Ffi.json$read(ret$, len$, de.ii.xtralink.jobs.PartialJob.class);
      Ffi.freeBytes(ret$);

      return out$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static void init(String id, de.ii.xtralink.jobs.InitProgress progress) {
    try (Arena arena = Arena.ofConfined()) {
      byte[] progress$json = Ffi.json$write(progress);
      Ffi.JobQueue_Init$MH.invokeExact(Ffi.str(arena, id), Ffi.bytes(arena, progress$json), progress$json == null ? 0L : (long) progress$json.length);
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static void updatePartial(String id, int delta) {
    try (Arena arena = Arena.ofConfined()) {
      Ffi.JobQueue_UpdatePartial$MH.invokeExact(Ffi.str(arena, id), delta);
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static boolean cancel(String id) {
    try (Arena arena = Arena.ofConfined()) {
      short ret$ = (short) Ffi.JobQueue_Cancel$MH.invokeExact(Ffi.str(arena, id));

      return ret$ == 1;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static java.util.Optional<de.ii.xtralink.jobs.Job> get(String id) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment clen$ = arena.allocate(Ffi.C_SIZE_T);
      MemorySegment cok$ = arena.allocate(Ffi.C_SHORT);
      MemorySegment ret$ = (MemorySegment) Ffi.JobQueue_Get$MH.invokeExact(Ffi.str(arena, id), clen$, cok$);
      long len$ = clen$.get(Ffi.C_SIZE_T, 0);

      if (cok$.get(Ffi.C_SHORT, 0) != 1) {
        Ffi.freeBytes(ret$);
        return java.util.Optional.empty();
      }

      de.ii.xtralink.jobs.Job out$ = Ffi.json$read(ret$, len$, de.ii.xtralink.jobs.Job.class);
      Ffi.freeBytes(ret$);

      return java.util.Optional.ofNullable(out$);
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static java.util.Optional<de.ii.xtralink.jobs.PartialJob> getPartial(String id) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment clen$ = arena.allocate(Ffi.C_SIZE_T);
      MemorySegment cok$ = arena.allocate(Ffi.C_SHORT);
      MemorySegment ret$ = (MemorySegment) Ffi.JobQueue_GetPartial$MH.invokeExact(Ffi.str(arena, id), clen$, cok$);
      long len$ = clen$.get(Ffi.C_SIZE_T, 0);

      if (cok$.get(Ffi.C_SHORT, 0) != 1) {
        Ffi.freeBytes(ret$);
        return java.util.Optional.empty();
      }

      de.ii.xtralink.jobs.PartialJob out$ = Ffi.json$read(ret$, len$, de.ii.xtralink.jobs.PartialJob.class);
      Ffi.freeBytes(ret$);

      return java.util.Optional.ofNullable(out$);
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static void register(String jobType, int priority, JobProcessor.Registration processor) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment cerr$ = arena.allocate(Ffi.C_POINTER);
      Ffi.JobQueue_Register$MH.invokeExact(Ffi.str(arena, jobType), priority, processor.id(), cerr$);

      MemorySegment err$ = cerr$.get(Ffi.C_POINTER, 0);

      if (err$.address() != 0) {
        String message$ = Ffi.str(err$);
        Ffi.freeString(err$);
        throw new FfiException(message$);
      }
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }
}
