// Code generated by genffi. DO NOT EDIT.

package main

/*
#include <string.h>
#include <stdlib.h>


*/
import "C"
import "errors"
import "fmt"
import "unsafe"
import "sync"
import "time"
import api "github.com/ldproxy/xtralink/ffi/api"
import clib "github.com/ldproxy/xtralink/ffi/clib"
import model "github.com/ldproxy/xtralink/model"

func main() {}

//=== INIT ===

var jobQueue api.JobQueue
	



type cInit interface {
	JobQueue() api.JobQueue
}

//export InitLibrary
func InitLibrary() {
	var init cInit = clib.NewInit()

	jobQueue = init.JobQueue()
}

//=== FUTURES ===

// A pending asynchronous operation.
//
// `done` is both the readiness signal and the only synchronization the payload needs: the
// goroutine writes result/ok/err *before* closing it, and an awaiting thread reads them
// *after* receiving from it, so the close is the happens-before edge. Adding a lock around
// the fields would be redundant, not safer.
//
// `handed` is the exception: it is written by whichever Ffi_WaitAny reports the id and read
// by every one after, which the close orders nothing about — so it is guarded by futures_mu,
// like the map it lives in.
type futureSlot struct {
	done   chan struct{}
	result any
	ok     bool
	err    error
	handed bool
}

// A map with a monotonic counter, unlike the handle tables, which are slices that only
// grow. The difference is lifetime: a handle index stays valid for the life of the process,
// while a future is consumed by the Await that collects it and its slot has to go back, or
// every call leaks one.
var (
	futures_mu   sync.Mutex
	futures      = map[int64]*futureSlot{}
	futures_next int64
	// Buffered to one, and sent without blocking: it is a *signal* that something completed,
	// not a carrier of which one — Ffi_WaitAny re-scans on every wake, so a full buffer
	// already says what a second send would. Dropping it is correct rather than lossy.
	futures_wake = make(chan struct{}, 1)
)

func newFuture() (*futureSlot, int64) {
	futures_mu.Lock()
	defer futures_mu.Unlock()
	futures_next++
	slot := &futureSlot{done: make(chan struct{})}
	futures[futures_next] = slot
	return slot, futures_next
}

func lookupFuture(id int64) *futureSlot {
	futures_mu.Lock()
	defer futures_mu.Unlock()
	return futures[id]
}

// readyFuture publishes a completed operation. Every goroutine that fills a slot ends here
// rather than closing `done` itself, because the close alone is invisible to a caller parked
// in Ffi_WaitAny — it has no channel to select on but this one.
func readyFuture(slot *futureSlot) {
	close(slot.done)

	select {
	case futures_wake <- struct{}{}:
	default:
	}
}

// handFuture claims one operation that has completed and has not been reported yet, or 0 if
// there is none. Split out of Ffi_WaitAny so the lock is held for the scan and nothing else.
func handFuture() int64 {
	futures_mu.Lock()
	defer futures_mu.Unlock()

	for id, slot := range futures {
		if slot.handed {
			continue
		}

		select {
		case <-slot.done:
			slot.handed = true
			return id
		default:
		}
	}

	return 0
}

// takeFuture blocks until the operation completes, then releases the slot. An id is good
// for exactly one await.
//
// An unknown id panics rather than blocking, which is the same policy the handle tables
// apply to a closed slot: the consumer-side wrapper is what guarantees each id is awaited
// once, and a panic crossing the FFI boundary takes the process — far easier to place than
// a thread parked forever on a channel nothing will ever close.
func takeFuture(id int64) *futureSlot {
	slot := lookupFuture(id)
	if slot == nil {
		panic(fmt.Sprintf("no pending operation with id %d: it was already awaited, or freed", id))
	}

	<-slot.done

	futures_mu.Lock()
	defer futures_mu.Unlock()
	delete(futures, id)
	return slot
}

// Future_Poll reports whether an operation has finished, without waiting for it. 1 when the
// result is ready to be awaited, 0 while it is still running.
//
// This is what a caller on an event loop uses instead of blocking a thread in the Await.
//export Future_Poll
func Future_Poll(future int64) C.short {
	slot := lookupFuture(future)
	if slot == nil {
		panic(fmt.Sprintf("no pending operation with id %d: it was already awaited, or freed", future))
	}

	select {
	case <-slot.done:
		return C.short(1)
	default:
		return C.short(0)
	}
}

// Future_Free detaches the caller from an operation and discards its result. Safe before or
// after completion, and safe to call on an id that no longer exists.
//
// It does not *cancel* anything: the goroutine runs to completion and its result is dropped
// on the floor. Any side effect the operation has still happens.
//export Future_Free
func Future_Free(future int64) {
	futures_mu.Lock()
	defer futures_mu.Unlock()
	delete(futures, future)
}

// Ffi_WaitAny blocks until *some* started operation has completed and hands back its id, or
// returns 0 when timeout_ms elapses first. The id is then awaited exactly as one the caller
// has been holding all along — the matching _Await returns without waiting, because the
// result is already there.
//
// This is the export that collapses the per-operation await thread: a caller runs one drain
// loop for the whole process instead of parking a thread inside every _Await. A thread pool
// cannot fix that on its own, because the thread is blocked in a downcall and stays blocked
// for as long as the operation takes.
//
// The timeout exists so a caller's drain loop can notice its own stop flag; it is not a
// polling interval, because the wait is a channel receive rather than a sleep. Which is also
// why there is no shutdown here to match Callback_Shutdown: a drain loop leaves by not
// calling this again, and nothing on the Go side is waiting for it.
//
// Two properties the caller depends on:
//
//   - **Each id is reported once.** The result stays in the registry until an _Await collects
//     it, so a second report would hand one operation to two collectors.
//   - **Readiness is *scanned*, not queued.** A caller that never calls this still completes
//     operations, and a queue of completed ids nobody drains would grow without bound. The map
//     is only ever as large as the number in flight.
//export Ffi_WaitAny
func Ffi_WaitAny(timeout_ms C.int) int64 {
	timer := time.NewTimer(time.Duration(timeout_ms) * time.Millisecond)
	defer timer.Stop()

	for {
		if id := handFuture(); id != 0 {
			return id
		}

		select {
		case <-futures_wake:
		case <-timer.C:
			return 0
		}
	}
}

// Future_Count is how many operations have been started and neither awaited nor freed. For
// tests and diagnostics: a count that does not come back to zero is a leak.
//export Future_Count
func Future_Count() int64 {
	futures_mu.Lock()
	defer futures_mu.Unlock()
	return int64(len(futures))
}

//=== CALLBACKS ===

// A posted upcall: which listener it is for, which method, and the arguments the
// implementation passed — still as Go values. They are converted to C only when the
// caller collects them, in the generated <Iface>_<Method>_Args accessor, so an
// invocation nobody drains costs no C memory.
type callbackInvocation struct {
	listener int64
	method   int32
	args     []any
	// Non-nil only for a two-way method, and the flag every branch below reads to tell the
	// two shapes apart: it is where the caller's answer is handed back, and its presence is
	// what says the invocation is not over when its arguments have been collected.
	answer chan callbackAnswer
}

// What a two-way callback answered: the value, whether it was present, and what it failed
// with. Only the legs the method declared are ever written — <Iface>_<Method>_Return's
// argument list is what decides, and the error leg is always there because twoWay *is*
// @throws.
type callbackAnswer struct {
	value any
	ok    bool
	err   error
}

// goError is the answer's error leg as it arrives: the caller's own string, NULL for success.
// C.GoString copies, so the string stays the caller's to free — the same borrow a downcall
// parameter is, because that is the direction this travels.
func goError(err *C.char) error {
	if err == nil {
		return nil
	}

	return errors.New(C.GoString(err))
}

var (
	callbacks_mu      sync.Mutex
	callbacks         = map[int64]bool{}
	callbacks_next    int64
	callbacks_queue   []*callbackInvocation
	callbacks_pending = map[int64]*callbackInvocation{}
	// Posted and not yet collected, per listener. The whole reason it is per listener and
	// not the one global count is Callback_Unregister, which has to wait for *this*
	// listener's backlog without being held up by anybody else's.
	callbacks_inflight = map[int64]int{}
	callbacks_inv      int64
	callbacks_done     bool
	// Buffered to one, and sent without blocking: it is a *signal* that the queue is
	// non-empty, not a carrier of the work. A full buffer already says what a second send
	// would, so dropping it is correct rather than lossy.
	callbacks_wake = make(chan struct{}, 1)
	callbacks_stop = make(chan struct{})
)

// Callback_Register allocates a listener id. The caller associates it with whatever object
// it will dispatch to and passes the id wherever the api declares a @callback parameter.
//export Callback_Register
func Callback_Register() int64 {
	callbacks_mu.Lock()
	defer callbacks_mu.Unlock()
	callbacks_next++
	callbacks[callbacks_next] = true
	return callbacks_next
}

// Callback_Unregister releases a listener id: no further invocation is accepted for it, and
// the call then **waits for the ones already posted to be collected**. Returns 1 when the
// listener drained, 0 when timeout_ms elapsed first.
//
// The wait is what makes the id safe to forget. Without it, unregistering immediately after
// a call that emitted would race the caller's own drain thread and discard the tail — and
// silently, because a dropped invocation looks exactly like one that was never made. That
// is the shape a caller hits *first*: emit through a listener, return, close.
//
// Pass timeout_ms = 0 to skip the wait, which is what a caller closing a registration from
// inside one of its own callbacks must do — the thread that would have to do the draining is
// the one asking, so waiting on it would be waiting for itself.
//
// Polled rather than signalled: the wait is normally over on the first check or the one
// after, and a condition variable here would need a second wake path beside callbacks_wake
// for no measurable gain.
//export Callback_Unregister
func Callback_Unregister(listener int64, timeout_ms C.int) C.short {
	callbacks_mu.Lock()
	delete(callbacks, listener)
	callbacks_mu.Unlock()

	deadline := time.Now().Add(time.Duration(timeout_ms) * time.Millisecond)

	for {
		callbacks_mu.Lock()
		inflight := callbacks_inflight[listener]
		callbacks_mu.Unlock()

		if inflight == 0 {
			return C.short(1)
		}
		if !time.Now().Before(deadline) {
			return C.short(0)
		}

		time.Sleep(200 * time.Microsecond)
	}
}

// postCallback queues an invocation and returns immediately.
//
// An invocation for a listener that is no longer registered is **dropped**, which is a
// deliberate departure from the handle tables' policy of panicking on a closed slot. A
// registration closing while the implementation is mid-emit is an ordinary race rather
// than a boundary violation, there is nobody left to deliver to, and taking the process
// for it would be wrong. Callback_Count is what makes the drop observable.
func postCallback(listener int64, method int32, args []any) {
	enqueueCallback(&callbackInvocation{listener: listener, method: method, args: args})
}

// enqueueCallback appends an invocation and wakes the drain, or reports false when there is
// nobody to deliver to. Shared by the two posts so the drop policy above has one definition —
// a two-way post drops for exactly the same reasons, and turns the false into the error its
// @throws requires.
func enqueueCallback(inv *callbackInvocation) bool {
	callbacks_mu.Lock()
	if callbacks_done || !callbacks[inv.listener] {
		callbacks_mu.Unlock()
		return false
	}
	callbacks_queue = append(callbacks_queue, inv)
	callbacks_inflight[inv.listener]++
	callbacks_mu.Unlock()

	select {
	case callbacks_wake <- struct{}{}:
	default:
	}

	return true
}

// postCallbackAnswer queues a two-way invocation and **blocks** until the caller answers it.
// That park is the whole cost of a callback that answers back: the goroutine that called the
// listener waits here for the generated <Iface>_<Method>_Return.
//
// Reports false when there is no answer to be had — the listener was not registered, or the
// queue was shut down while this goroutine was parked. The proxy turns that into the error the
// method's @throws requires, so a dropped round trip is reported to the implementation rather
// than answered with an invented zero.
//
// Selecting on callbacks_stop is what makes Callback_Shutdown a release valve. Without it,
// shutting the queue down would strand every goroutine parked here with nothing left that
// could ever wake them.
func postCallbackAnswer(listener int64, method int32, args []any) (callbackAnswer, bool) {
	inv := &callbackInvocation{
		listener: listener,
		method:   method,
		args:     args,
		// Buffered to one, and there is only ever one send: returnCallback must not block on
		// a goroutine that has already given up and left through callbacks_stop.
		answer: make(chan callbackAnswer, 1),
	}

	if !enqueueCallback(inv) {
		return callbackAnswer{}, false
	}

	select {
	case answer := <-inv.answer:
		return answer, true
	case <-callbacks_stop:
		return callbackAnswer{}, false
	}
}

// takeCallback collects a posted invocation's arguments and releases its slot. An id is
// good for exactly one collection, and an unknown one panics — the same policy takeFuture
// applies, and for the same reason: the caller-side wrapper is what guarantees one
// accessor call per id.
func takeCallback(inv int64) *callbackInvocation {
	callbacks_mu.Lock()
	defer callbacks_mu.Unlock()

	slot := callbacks_pending[inv]
	if slot == nil {
		panic(fmt.Sprintf("no pending callback with id %d: its arguments were already collected", inv))
	}

	// A two-way invocation is only *half* over here. Its arguments have been collected, but
	// the emitting goroutine is still parked and returnCallback is what releases both the
	// slot and the listener's inflight count — so Callback_Unregister's wait covers the whole
	// round trip rather than just its outbound leg.
	if slot.answer != nil {
		return slot
	}
	delete(callbacks_pending, inv)

	// Decremented here rather than after the listener runs, and for a fire-and-forget
	// invocation that is exactly far enough: the caller reads the target *before* collecting
	// the arguments, so once this reaches zero every invocation for the listener has already
	// been bound to its object and Callback_Unregister may return.
	if callbacks_inflight[slot.listener] > 1 {
		callbacks_inflight[slot.listener]--
	} else {
		delete(callbacks_inflight, slot.listener)
	}

	return slot
}

// returnCallback hands a two-way callback's answer to the parked goroutine and releases its
// slot — the half of the invocation takeCallback deliberately left outstanding, and what the
// generated <Iface>_<Method>_Return calls.
//
// An unknown id panics, the same policy takeCallback and takeFuture apply: the caller-side
// wrapper is what guarantees exactly one _Return per two-way invocation, so a second one is a
// boundary violation rather than a race. The one exception is during teardown, where the
// parked goroutine has already left through callbacks_stop — there is nothing to deliver and
// nobody to report to, and a panic crossing the boundary mid-shutdown would be worse than
// silence.
func returnCallback(inv int64, answer callbackAnswer) {
	callbacks_mu.Lock()

	slot := callbacks_pending[inv]
	if slot == nil || slot.answer == nil {
		done := callbacks_done
		callbacks_mu.Unlock()

		if done {
			return
		}

		panic(fmt.Sprintf("no two-way callback with id %d awaiting an answer: it was already answered, or the method is fire-and-forget", inv))
	}

	delete(callbacks_pending, inv)

	if callbacks_inflight[slot.listener] > 1 {
		callbacks_inflight[slot.listener]--
	} else {
		delete(callbacks_inflight, slot.listener)
	}
	callbacks_mu.Unlock()

	// Buffered to one and the only send, so this cannot block — including on a goroutine that
	// gave up during shutdown and is no longer receiving.
	slot.answer <- answer
}

// Callback_Next blocks until an invocation is pending and hands back its id, writing the
// listener and the global method ordinal to the out-parameters. Returns 0 when the timeout
// elapses or the queue has been shut down.
//
// The timeout exists so a caller's drain loop can notice its own stop flag; it is not a
// polling interval, because the wait is a channel receive rather than a sleep. Having been
// handed an id, the caller MUST call the matching <Iface>_<Method>_Args accessor exactly
// once — that is what releases the slot.
//export Callback_Next
func Callback_Next(timeout_ms C.int, listener *C.longlong, method *C.int) int64 {
	timer := time.NewTimer(time.Duration(timeout_ms) * time.Millisecond)
	defer timer.Stop()

	for {
		callbacks_mu.Lock()
		if len(callbacks_queue) > 0 {
			slot := callbacks_queue[0]
			callbacks_queue[0] = nil
			callbacks_queue = callbacks_queue[1:]
			callbacks_inv++
			inv := callbacks_inv
			callbacks_pending[inv] = slot
			callbacks_mu.Unlock()

			*listener = C.longlong(slot.listener)
			*method = C.int(slot.method)
			return inv
		}
		callbacks_mu.Unlock()

		select {
		case <-callbacks_wake:
		case <-callbacks_stop:
			return 0
		case <-timer.C:
			return 0
		}
	}
}

// Callback_Shutdown stops delivery for good: every blocked Callback_Next returns 0, the
// queue is discarded and nothing further is posted. For an orderly teardown, not a pause —
// there is no way back.
//export Callback_Shutdown
func Callback_Shutdown() {
	callbacks_mu.Lock()
	defer callbacks_mu.Unlock()

	if callbacks_done {
		return
	}
	callbacks_done = true
	callbacks_queue = nil
	// Cleared with the queue, or a Callback_Unregister after shutdown would wait out its
	// whole timeout for invocations that have just been discarded.
	callbacks_inflight = map[int64]int{}
	close(callbacks_stop)
}

// Callback_Count is how many invocations have been posted and not yet collected, queued and
// handed-out alike. For tests and diagnostics: a count that does not come back to zero is a
// listener nobody is draining.
//export Callback_Count
func Callback_Count() int64 {
	callbacks_mu.Lock()
	defer callbacks_mu.Unlock()
	return int64(len(callbacks_queue) + len(callbacks_pending))
}


//=== JobListener (callback) ===

var _ api.JobListener = (*cbJobListener)(nil)

type cbJobListener struct{ id int64 }

func (recv *cbJobListener) OnProgress(job model.Job) {
	postCallback(recv.id, 0, []any{job})
}

//export JobListener_OnProgress_Args
	func JobListener_OnProgress_Args(inv int64, job **C.char, job_length *C.size_t)  {
		args := takeCallback(inv).args
		job_arg := model.MarshalJob(args[0].(model.Job))
		*job = (*C.char)(C.CBytes(job_arg))
		*job_length = C.size_t(len(job_arg))
	}

//=== JobProcessor (callback) ===

var _ api.JobProcessor = (*cbJobProcessor)(nil)

type cbJobProcessor struct{ id int64 }

func (recv *cbJobProcessor) Process(partialJob model.PartialJob, job model.Job) (model.JobResult, error){
	answer, delivered := postCallbackAnswer(recv.id, 1, []any{partialJob, job})
	if !delivered {
		var zero model.JobResult
		return zero, fmt.Errorf("callback %s was not delivered: the listener is closed, or the callback queue has been shut down", "Process")
	}
	value, _ := answer.value.(model.JobResult)
	return value, answer.err
}

//export JobProcessor_Process_Args
	func JobProcessor_Process_Args(inv int64, partialJob **C.char, partialJob_length *C.size_t, job **C.char, job_length *C.size_t)  {
		args := takeCallback(inv).args
		partialJob_arg := model.MarshalPartialJob(args[0].(model.PartialJob))
		*partialJob = (*C.char)(C.CBytes(partialJob_arg))
		*partialJob_length = C.size_t(len(partialJob_arg))
		job_arg := model.MarshalJob(args[1].(model.Job))
		*job = (*C.char)(C.CBytes(job_arg))
		*job_length = C.size_t(len(job_arg))
	}

//export JobProcessor_Process_Return
	func JobProcessor_Process_Return(inv int64, value *C.char, value_length C.size_t, err *C.char)  {
		value_value, value_err := model.UnmarshalJobResult(C.GoBytes(unsafe.Pointer(value), C.int(value_length)))
		if value_err != nil {
			returnCallback(inv, callbackAnswer{err: value_err})
			return
		}
		returnCallback(inv, callbackAnswer{value: value_value, err: goError(err)})
	}


//=== JobQueue ===

//export JobQueue_Start
	func JobQueue_Start(cfg *C.char, cfg_length C.size_t, cerr **C.char)  {
		cfg_value, cfg_err := model.UnmarshalQueueConfiguration(C.GoBytes(unsafe.Pointer(cfg), C.int(cfg_length)))
  if cfg_err != nil {
    *cerr = C.CString(cfg_err.Error())
    return
  }
  err := jobQueue.Start(cfg_value)
  if err != nil { *cerr = C.CString(err.Error()) }
	}

//export JobQueue_Stop
	func JobQueue_Stop()  {
		jobQueue.Stop()
	}

//export JobQueue_Push
	func JobQueue_Push(job *C.char, job_length C.size_t, onProgress int64, clen *C.size_t) *C.char {
		job_value, job_err := model.UnmarshalJobConfiguration(C.GoBytes(unsafe.Pointer(job), C.int(job_length)))
  if job_err != nil { panic(fmt.Sprintf("job: %v", job_err)) }
  result := model.MarshalJob(jobQueue.Push(job_value, &cbJobListener{id: onProgress}))
  *clen = C.size_t(len(result))
  return (*C.char)(C.CBytes(result))
	}

//export JobQueue_PushPartial
	func JobQueue_PushPartial(partialJob *C.char, partialJob_length C.size_t, clen *C.size_t) *C.char {
		partialJob_value, partialJob_err := model.UnmarshalPartialJobConfiguration(C.GoBytes(unsafe.Pointer(partialJob), C.int(partialJob_length)))
  if partialJob_err != nil { panic(fmt.Sprintf("partialJob: %v", partialJob_err)) }
  result := model.MarshalPartialJob(jobQueue.PushPartial(partialJob_value))
  *clen = C.size_t(len(result))
  return (*C.char)(C.CBytes(result))
	}

//export JobQueue_RepushPartial
	func JobQueue_RepushPartial(id *C.char, clen *C.size_t) *C.char {
		result := model.MarshalPartialJob(jobQueue.RepushPartial(C.GoString(id)))
  *clen = C.size_t(len(result))
  return (*C.char)(C.CBytes(result))
	}

//export JobQueue_WaitFor_Start
	func JobQueue_WaitFor_Start(id *C.char) int64 {
		fut, future := newFuture()
  go func(recv api.JobQueue, id string) {
    result := recv.WaitFor(id)
    fut.result = result
    readyFuture(fut)
  }(jobQueue, C.GoString(id))
  return future
	}

//export JobQueue_WaitFor_Await
	func JobQueue_WaitFor_Await(future int64, clen *C.size_t) *C.char {
		fut := takeFuture(future)
  result, _ := fut.result.(model.Job)
  result_json := model.MarshalJob(result)
  *clen = C.size_t(len(result_json))
  return (*C.char)(C.CBytes(result_json))
	}

//export JobQueue_WaitForPartial_Start
	func JobQueue_WaitForPartial_Start(id *C.char) int64 {
		fut, future := newFuture()
  go func(recv api.JobQueue, id string) {
    result := recv.WaitForPartial(id)
    fut.result = result
    readyFuture(fut)
  }(jobQueue, C.GoString(id))
  return future
	}

//export JobQueue_WaitForPartial_Await
	func JobQueue_WaitForPartial_Await(future int64, clen *C.size_t) *C.char {
		fut := takeFuture(future)
  result, _ := fut.result.(model.PartialJob)
  result_json := model.MarshalPartialJob(result)
  *clen = C.size_t(len(result_json))
  return (*C.char)(C.CBytes(result_json))
	}

//export JobQueue_Init
	func JobQueue_Init(id *C.char, progress *C.char, progress_length C.size_t)  {
		progress_value, progress_err := model.UnmarshalInitProgress(C.GoBytes(unsafe.Pointer(progress), C.int(progress_length)))
  if progress_err != nil { panic(fmt.Sprintf("progress: %v", progress_err)) }
  jobQueue.Init(C.GoString(id), progress_value)
	}

//export JobQueue_UpdatePartial
	func JobQueue_UpdatePartial(id *C.char, delta C.int)  {
		jobQueue.UpdatePartial(C.GoString(id), int32(delta))
	}

//export JobQueue_Outputs
	func JobQueue_Outputs(id *C.char, outputs *C.char, outputs_length C.size_t)  {
		outputs_value, outputs_err := model.UnmarshalSetOutputs(C.GoBytes(unsafe.Pointer(outputs), C.int(outputs_length)))
  if outputs_err != nil { panic(fmt.Sprintf("outputs: %v", outputs_err)) }
  jobQueue.Outputs(C.GoString(id), outputs_value)
	}

//export JobQueue_Cancel
	func JobQueue_Cancel(id *C.char) C.short {
		return CBool(jobQueue.Cancel(C.GoString(id)))
	}

//export JobQueue_Get
	func JobQueue_Get(id *C.char, clen *C.size_t, cok *C.short) *C.char {
		result, ok := jobQueue.Get(C.GoString(id))
  if ok { *cok = 1 } else { *cok = 0 }
  result_json := model.MarshalJob(result)
  *clen = C.size_t(len(result_json))
  return (*C.char)(C.CBytes(result_json))
	}

//export JobQueue_GetPartial
	func JobQueue_GetPartial(id *C.char, clen *C.size_t, cok *C.short) *C.char {
		result, ok := jobQueue.GetPartial(C.GoString(id))
  if ok { *cok = 1 } else { *cok = 0 }
  result_json := model.MarshalPartialJob(result)
  *clen = C.size_t(len(result_json))
  return (*C.char)(C.CBytes(result_json))
	}

//export JobQueue_Register
	func JobQueue_Register(jobType *C.char, priority C.int, processor int64, cerr **C.char)  {
		err := jobQueue.Register(C.GoString(jobType), int32(priority), &cbJobProcessor{id: processor})
  if err != nil { *cerr = C.CString(err.Error()) }
	}


//=== ENUMS ===



//=== STRUCTS ===



//=== FREE ===


//export FreeString
func FreeString(str *C.char) {
	C.free(unsafe.Pointer(str))
}

//export FreeBytes
func FreeBytes(bytes *C.char) {
	C.free(unsafe.Pointer(bytes))
}

// FreeArray releases the backing storage of a *returned* array — the single C.malloc
// CMapSlice made for it. The elements are not touched: an element that owns memory has to
// be released first, one at a time, because only the caller knows how many there are.
//
// It is C.free like the two above, and takes *C.char only because every pointer converts
// to one; the array may just as well be a **C.char or a *C.Source. Named separately all
// the same, since a returned array has no Free<Struct> of its own to hang this off and a
// caller reaching for FreeString on a **C.char has to stop and wonder whether that is
// right.
//export FreeArray
func FreeArray(array *C.char) {
	C.free(unsafe.Pointer(array))
}




//=== UTIL ===


func CBool(flag bool) C.short {
	if flag {
		return C.short(1)
	}
	return C.short(0)
}

func GoMapSlice[T, U any](source *T, length int, f func(*T) U) []U {
	target := make([]U, 0, length)
	for _, t := range unsafe.Slice(source, length) {
		target = append(target, f(&t))
	}
	return target
}

// The result is C-allocated and owned by the caller, who must release it with
// the generated Free* functions.
func CMapSlice[T, U any](source []T, f func(T) U) *U {
	if len(source) == 0 {
		return nil
	}
	var zero U
	target := (*U)(C.malloc(C.size_t(len(source)) * C.size_t(unsafe.Sizeof(zero))))
	slice := unsafe.Slice(target, len(source))
	for i, t := range source {
		slice[i] = f(t)
	}
	return target
}

// Per-element converters for arrays of basic types. GoMapSlice and CMapSlice are handed
// one converter per element, and only custom types have one generated for them
// (GoSource / CSource); these serve the basic elements. Each C-allocated string in a
// returned array is owned by the caller, exactly as a bare string return is.
func GoElemString(fromC **C.char) string { return C.GoString(*fromC) }

func CElemString(fromGo string) *C.char { return C.CString(fromGo) }

func GoElemFloat64(fromC *C.double) float64 { return float64(*fromC) }

func CElemFloat64(fromGo float64) C.double { return C.double(fromGo) }

func GoElemInt64(fromC *C.longlong) int64 { return int64(*fromC) }

func CElemInt64(fromGo int64) C.longlong { return C.longlong(fromGo) }

func GoElemInt32(fromC *C.int) int32 { return int32(*fromC) }

func CElemInt32(fromGo int32) C.int { return C.int(fromGo) }

func GoElemBool(fromC *C.short) bool { return *fromC == 1 }

func CElemBool(fromGo bool) C.short { return CBool(fromGo) }

    