plugins {
    id 'java-library'
}

group = 'de.interactive_instruments'

version = '0.9.3'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.21.0'
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jdk8', version: '2.21.0'
}

java {
    withJavadocJar()
    withSourcesJar()
}
