// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs.api;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * The native boundary. Generated — do not edit.
 *
 * <p>Package-private on purpose: every symbol, layout and offset below is an
 * implementation detail of the wrapper classes beside it, and none of it is part of the
 * API this package offers. See {@code docs/guide/java-binding.md}.
 *
 * <p>Requires Java 22 or later, and {@code --enable-native-access} for whatever owns this
 * class.
 */
// Restricted methods — libraryLookup, downcallHandle and reinterpret — are the point of
// this class, and the caller has already had to grant native access to load it at all.
// Suppressed here and nowhere else, so the warning still means something everywhere else.
@SuppressWarnings("restricted")
final class Ffi {
  private Ffi() {}

  private static final String LIB = "xtralink";

  private static final Linker LINKER = Linker.nativeLinker();
  private static final SymbolLookup LOOKUP = load();

  private static final java.util.Map<String, MemoryLayout> CANONICAL = LINKER.canonicalLayouts();

  static final ValueLayout.OfShort C_SHORT = (ValueLayout.OfShort) CANONICAL.get("short");
  static final ValueLayout.OfInt C_INT = (ValueLayout.OfInt) CANONICAL.get("int");
  static final ValueLayout.OfLong C_LONG_LONG = (ValueLayout.OfLong) CANONICAL.get("long long");
  static final ValueLayout.OfDouble C_DOUBLE = (ValueLayout.OfDouble) CANONICAL.get("double");
  static final ValueLayout.OfByte C_CHAR = (ValueLayout.OfByte) CANONICAL.get("char");
  static final AddressLayout C_POINTER = (AddressLayout) CANONICAL.get("void*");
  static final ValueLayout.OfLong C_SIZE_T = (ValueLayout.OfLong) CANONICAL.get("size_t");

  /**
   * Set {@code -Dgenffi.library.xtralink=/path/to/libxtralink.so} to load one explicit file;
   * otherwise the library is resolved the usual way, through {@code java.library.path}.
   */
  private static SymbolLookup load() {
    String explicit = System.getProperty("genffi.library." + LIB);

    if (explicit != null) {
      return SymbolLookup.libraryLookup(java.nio.file.Path.of(explicit), Arena.global());
    }

    System.loadLibrary(LIB);

    return SymbolLookup.loaderLookup().or(Linker.nativeLinker().defaultLookup());
  }

  private static MethodHandle downcall(String symbol, FunctionDescriptor descriptor) {
    return LINKER.downcallHandle(
        LOOKUP.find(symbol).orElseThrow(
            () -> new UnsatisfiedLinkError("no symbol " + symbol + " in " + LIB)),
        descriptor);
  }

  /**
   * {@code invokeExact} is declared {@code throws Throwable}, and for a correctly
   * generated descriptor none of it can happen. Unwrapped rather than swallowed, so a
   * genuine {@code Error} still propagates as itself.
   */
  static RuntimeException rethrow(Throwable t) {
    if (t instanceof RuntimeException e) {
      throw e;
    }
    if (t instanceof Error e) {
      throw e;
    }

    return new FfiException(t);
  }


  static MemorySegment str(SegmentAllocator alloc, String value) {
    return value == null ? MemorySegment.NULL : alloc.allocateFrom(value);
  }

  static String str(MemorySegment p) {
    // A segment returned from a downcall has length zero — its address is all the callee
    // gave us — so it has to be widened before anything may be read through it.
    return p.address() == 0 ? null : p.reinterpret(Long.MAX_VALUE).getString(0);
  }

  static MemorySegment bytes(SegmentAllocator alloc, byte[] value) {
    return value == null || value.length == 0
        ? MemorySegment.NULL
        : alloc.allocateFrom(C_CHAR, value);
  }

  /** Never {@code strlen}: the payload may contain NUL, which is why {@code clen} exists. */
  static byte[] bytes(MemorySegment p, long len) {
    return p.address() == 0 || len == 0
        ? new byte[0]
        : p.reinterpret(len).toArray(C_CHAR);
  }

  private static final ObjectMapper JSON = new ObjectMapper();

  static byte[] json$write(Object value) {
    try {
      return value == null ? new byte[0] : JSON.writeValueAsBytes(value);
    } catch (Exception e) {
      throw new FfiException(e);
    }
  }

  /**
   * Reads the payload the library allocated. A zero-length one means the call produced no
   * value — a {@code @throws} method that failed, whose error the caller reads from
   * {@code cerr} instead — so it is null rather than a parse failure.
   */
  static <T> T json$read(MemorySegment p, long len, Class<T> type) {
    byte[] data = bytes(p, len);

    if (data.length == 0) {
      return null;
    }

    try {
      return JSON.readValue(data, type);
    } catch (Exception e) {
      throw new FfiException(e);
    }
  }

  //=== FUTURES ===

  private static final MethodHandle Ffi_WaitAny$MH =
      downcall("Ffi_WaitAny", FunctionDescriptor.of(C_LONG_LONG, C_INT));

  /**
   * Runs the collection of a completed operation, and nothing else. One task per operation
   * that <b>finishes</b>, each of them brief: the {@code _Await} it makes returns without
   * waiting, because {@link #drain$} only hands over ids the library has already reported.
   *
   * <p>Not the drain thread itself, and that is the whole reason this pool is still here.
   * Completing a {@code CompletableFuture} runs every dependent the caller attached, on the
   * completing thread — so a continuation that blocks, {@code thenApply(v -> other.join())}
   * being the obvious one, would wedge the one thread that notices completions and deadlock
   * outright.
   *
   * <p>Daemon threads: an unawaited operation must never keep the JVM alive.
   */
  private static final java.util.concurrent.ExecutorService ASYNC =
      java.util.concurrent.Executors.newCachedThreadPool(
          r -> {
            Thread t = new Thread(r, "genffi-collect");
            t.setDaemon(true);
            return t;
          });

  /**
   * Stands in for an id the drain thread reported before {@link #pending$} had recorded
   * anything to hand it to — the library can finish an operation before {@code _Start} has
   * even returned its id, and a short one usually does.
   *
   * <p>{@link #PENDING} is the rendezvous between the two: whichever arrives second finds the
   * other's entry and dispatches. Every access is one atomic map operation, so exactly one of
   * them does.
   */
  private static final Object READY = new Object();

  /**
   * Started operations, by the id the library allocated: either the collection waiting to be
   * run, or {@link #READY}. An entry covers one operation and is removed by whoever
   * dispatches it.
   */
  private static final java.util.concurrent.ConcurrentHashMap<Long, Object> PENDING =
      new java.util.concurrent.ConcurrentHashMap<>();

  private static Thread AWAITS;

  /**
   * Records how a started operation is collected and returns the future it will fill.
   *
   * <p>Called by every async method after its {@code _Start}, with the id that call returned.
   * The collection is not run here — it is run when the library says the result is there.
   */
  static <T> java.util.concurrent.CompletableFuture<T> pending$(
      long id, java.util.function.Supplier<T> collect) {
    java.util.concurrent.CompletableFuture<T> future =
        new java.util.concurrent.CompletableFuture<>();

    Runnable settle =
        () -> {
          try {
            future.complete(collect.get());
          } catch (Throwable t) {
            // A @throws method arrives here, and this is what makes join() throw a
            // CompletionException whose cause is the FfiException.
            future.completeExceptionally(t);
          }
        };

    startAwaits$();

    // READY: the operation completed, and was reported, before we got here. Ours is then the
    // second arrival, so ours is the dispatch.
    if (PENDING.put(id, settle) == READY) {
      PENDING.remove(id, settle);
      ASYNC.execute(settle);
    }

    return future;
  }

  /**
   * Starts the drain thread on the first async call, so a consumer that only makes
   * synchronous calls starts no thread at all — the same way one that registers no listener
   * starts no upcall thread.
   */
  private static synchronized void startAwaits$() {
    if (AWAITS == null) {
      AWAITS = new Thread(Ffi::drain$, "genffi-await");
      AWAITS.setDaemon(true);
      AWAITS.start();
    }
  }

  /**
   * Blocks in {@code Ffi_WaitAny} until some operation completes, then hands its collection to
   * {@link #ASYNC}. One thread, whatever the number in flight.
   *
   * <p>The 250ms timeout is not a polling interval — the wait on the Go side is a channel
   * receive, so a completion is picked up as soon as it happens. It exists only so this loop
   * comes back around periodically instead of parking in native code forever.
   */
  private static void drain$() {
    while (true) {
      long id;

      try {
        id = (long) Ffi_WaitAny$MH.invokeExact(250);
      } catch (Throwable t) {
        // The registry itself failed, which nothing here can recover from. Ending the thread
        // beats spinning on it: every operation still in flight stays unfinished, which is at
        // least visible in a stack dump, unlike a thread burning a core.
        System.err.println("genffi: await drain stopped");
        t.printStackTrace();
        return;
      }

      if (id == 0) {
        continue;
      }

      Object entry = PENDING.putIfAbsent(id, READY);

      // Absent: reported before pending$ recorded its collection, so READY is left behind for
      // it to find. Present: the collection is ours to run.
      if (entry != null) {
        PENDING.remove(id, entry);
        ASYNC.execute((Runnable) entry);
      }
    }
  }

  //=== CALLBACKS ===

  /**
   * The pool two-way callbacks run on — see {@code docs/guide/callbacks.md} §6.
   *
   * <p>Not the drain thread, and that is the whole point rather than a refinement. A callback
   * that answers back parks a goroutine inside the library until its {@code _Return} arrives,
   * so a listener run <b>on</b> the drain thread could not call back into the library: the
   * invocation it posted would be waiting for the very thread sitting inside its downcall.
   * Running listeners here leaves the drain loop free to pick that nested invocation up.
   *
   * <p>Cached and unbounded, so no nesting depth defeats it. Daemon, so an unanswered callback
   * never holds the JVM open.
   */
  private static final java.util.concurrent.ExecutorService ANSWERS =
      java.util.concurrent.Executors.newCachedThreadPool(
          r -> {
            Thread t = new Thread(r, "genffi-answer");
            t.setDaemon(true);
            return t;
          });

  private static void JobProcessor_Process$answer(
      long inv, Object listener$, de.ii.xtralink.jobs.Job job) {
    de.ii.xtralink.jobs.JobResult value = null;
    String err = null;

    try {
      if (listener$ == null) {
        // The registration was closed between the post and this task, so there is nobody to
        // ask. Reported as a failure rather than skipped: the goroutine is parked on an answer
        // and something has to arrive, and a silent zero would be a fabricated one.
        throw new IllegalStateException(
            "the listener was unregistered before this callback could be answered");
      }

      value = ((JobProcessor) listener$).process(job);
    } catch (Throwable t) {
      // Everything the listener can do wrong ends up here and travels back as the error the
      // method's @throws promised. Nothing may propagate out of this task: the thread is the
      // pool's, there is no caller to receive it, and a goroutine is waiting.
      err = t.toString();
    }

    try (Arena arena = Arena.ofConfined()) {
      MemorySegment value$ = value == null ? MemorySegment.NULL : bytes(arena, json$write(value));
      long value$n = value$.byteSize();
      MemorySegment err$ = str(arena, err);

      JobProcessor_Process_Return$MH.invokeExact(inv, value$, value$n, err$);
    } catch (Throwable t) {
      // The answer itself could not be delivered, which nothing here can retry — the arena is
      // gone and the value with it. The parked goroutine stays parked until the queue is shut
      // down, and Callback_Count is what shows it.
      System.err.println("genffi: could not answer callback JobProcessor_Process");
      t.printStackTrace();
    }
  }


  private static final MethodHandle Callback_Register$MH =
      downcall("Callback_Register", FunctionDescriptor.of(C_LONG_LONG));

  private static final MethodHandle Callback_Unregister$MH =
      downcall("Callback_Unregister", FunctionDescriptor.of(C_SHORT, C_LONG_LONG, C_INT));

  /**
   * How long {@link #unregister$} waits for a listener's already-posted invocations to be
   * collected before giving up on them. Generous, because reaching it at all means the drain
   * thread is wedged rather than merely busy.
   */
  private static final int DRAIN_MS = 2000;

  private static final MethodHandle Callback_Next$MH =
      downcall("Callback_Next", FunctionDescriptor.of(C_LONG_LONG, C_INT, C_POINTER, C_POINTER));

  /**
   * The live listeners, by the id {@code Callback_Register} allocated. The library holds the
   * id; this map holds the object, and neither side can see the other's half.
   */
  private static final java.util.concurrent.ConcurrentHashMap<Long, Object> LISTENERS =
      new java.util.concurrent.ConcurrentHashMap<>();

  private static Thread UPCALLS;

  /**
   * Registers a listener and starts the drain thread if this is the first one — so a binding
   * whose consumer never registers anything starts no thread at all, the same way a
   * synchronous one starts no await pool.
   */
  static synchronized long register$(Object implementation) {
    long id;

    try {
      id = (long) Callback_Register$MH.invokeExact();
    } catch (Throwable t) {
      throw rethrow(t);
    }

    LISTENERS.put(id, implementation);

    if (UPCALLS == null) {
      UPCALLS = new Thread(Ffi::pump$, "genffi-upcall");
      UPCALLS.setDaemon(true);
      UPCALLS.start();
    }

    return id;
  }

  /**
   * Stops delivery to a listener and waits for what the library has already posted to be
   * collected.
   *
   * <p>The wait is the whole of what makes closing safe. Emitting through a listener and
   * closing the registration on the next line is the *first* thing a caller writes, and the
   * queue is asynchronous — so without it the tail of the call's own callbacks would be
   * discarded, and discarded silently, because a dropped invocation is indistinguishable
   * from one that was never made.
   *
   * <p>Removing from {@code LISTENERS} only afterwards is the other half: {@link #dispatch$}
   * reads its target before collecting the arguments, so once the library reports the
   * listener drained, every invocation for it has already found its object.
   *
   * <p>Closing from inside one of your own callbacks skips the wait, and must: the drain
   * thread is the thread that would have to do the draining, so waiting on it here would be
   * waiting for ourselves.
   */
  static void unregister$(long id) {
    int timeout = Thread.currentThread() == UPCALLS ? 0 : DRAIN_MS;

    try {
      short drained = (short) Callback_Unregister$MH.invokeExact(id, timeout);

      if (drained == 0 && timeout > 0) {
        System.err.println(
            "genffi: listener " + id + " still had callbacks pending after " + timeout
                + "ms; they will not be delivered");
      }
    } catch (Throwable t) {
      throw rethrow(t);
    }

    LISTENERS.remove(id);
  }

  /**
   * Blocks in {@code Callback_Next} until the library posts something, then dispatches it.
   *
   * <p>The 250ms timeout is not a polling interval — the wait on the Go side is a channel
   * receive, so an invocation is picked up as soon as it is posted. It exists only so this
   * loop comes back around periodically instead of parking in native code forever.
   */
  private static void pump$() {
    while (true) {
      long inv;
      long listener;
      int method;

      try (Arena arena = Arena.ofConfined()) {
        MemorySegment listener$ = arena.allocate(C_LONG_LONG);
        MemorySegment method$ = arena.allocate(C_INT);

        inv = (long) Callback_Next$MH.invokeExact(250, listener$, method$);

        if (inv == 0) {
          continue;
        }

        listener = listener$.get(C_LONG_LONG, 0);
        method = method$.get(C_INT, 0);
      } catch (Throwable t) {
        // The queue itself failed, which nothing here can recover from. Ending the thread
        // beats spinning on it — every later invocation is dropped, and the count says so.
        System.err.println("genffi: callback drain stopped");
        t.printStackTrace();
        return;
      }

      try {
        dispatch$(inv, listener, method);
      } catch (Throwable t) {
        // A listener that throws must not take the drain thread with it: there is no caller
        // to propagate to, and the next invocation is already queued behind this one.
        System.err.println("genffi: listener threw for callback method " + method);
        t.printStackTrace();
      }
    }
  }

  /**
   * Collects one invocation's arguments and calls the listener.
   *
   * <p>The arguments are collected <b>whether or not the listener is still registered</b>:
   * the accessor is what releases the library's slot, so skipping it for a closed
   * registration would leak one invocation per event in flight at close time.
   */
  private static void dispatch$(long inv, long listener, int method) {
    Object target = LISTENERS.get(listener);

    switch (method) {
      case 0 -> {
        de.ii.xtralink.jobs.Job job;

        try (Arena arena = Arena.ofConfined()) {
          MemorySegment job$ = arena.allocate(C_POINTER);
          MemorySegment job$len = arena.allocate(C_SIZE_T);
          JobListener_OnProgress_Args$MH.invokeExact(inv, job$, job$len);
          var job$p = job$.get(C_POINTER, 0);
          long job$n = job$len.get(C_SIZE_T, 0);
          job = json$read(job$p, job$n, de.ii.xtralink.jobs.Job.class);
          freeBytes(job$p);
        } catch (Throwable t) {
          throw rethrow(t);
        }

        if (target != null) {
          ((JobListener) target).onProgress(job);
        }
      }

      case 1 -> {
        de.ii.xtralink.jobs.Job job;

        try (Arena arena = Arena.ofConfined()) {
          MemorySegment job$ = arena.allocate(C_POINTER);
          MemorySegment job$len = arena.allocate(C_SIZE_T);
          JobProcessor_Process_Args$MH.invokeExact(inv, job$, job$len);
          var job$p = job$.get(C_POINTER, 0);
          long job$n = job$len.get(C_SIZE_T, 0);
          job = json$read(job$p, job$n, de.ii.xtralink.jobs.Job.class);
          freeBytes(job$p);
        } catch (Throwable t) {
          throw rethrow(t);
        }

        ANSWERS.execute(
            () -> JobProcessor_Process$answer(
                inv, target, job));
      }

      default -> throw new IllegalStateException("unknown callback method ordinal " + method);
    }
  }

  //=== FIXED FREE FUNCTIONS ===

  private static final MethodHandle FreeString$MH =
      downcall("FreeString", FunctionDescriptor.ofVoid(C_POINTER));

  private static final MethodHandle FreeBytes$MH =
      downcall("FreeBytes", FunctionDescriptor.ofVoid(C_POINTER));

  private static final MethodHandle FreeArray$MH =
      downcall("FreeArray", FunctionDescriptor.ofVoid(C_POINTER));

  static void freeString(MemorySegment p) {
    try {
      FreeString$MH.invokeExact(p);
    } catch (Throwable t) {
      throw rethrow(t);
    }
  }

  static void freeBytes(MemorySegment p) {
    try {
      FreeBytes$MH.invokeExact(p);
    } catch (Throwable t) {
      throw rethrow(t);
    }
  }

  static void freeArray(MemorySegment p) {
    try {
      FreeArray$MH.invokeExact(p);
    } catch (Throwable t) {
      throw rethrow(t);
    }
  }

  //=== ENUMS ===

  //=== LAYOUTS ===


  //=== MARSHALING ===

  //=== ARRAYS ===

  //=== STRUCT FREE FUNCTIONS ===

  //=== EXPORTS ===

  static final MethodHandle JobListener_OnProgress_Args$MH =
      downcall("JobListener_OnProgress_Args", FunctionDescriptor.ofVoid(C_LONG_LONG, C_POINTER, C_POINTER));

  static final MethodHandle JobProcessor_Process_Args$MH =
      downcall("JobProcessor_Process_Args", FunctionDescriptor.ofVoid(C_LONG_LONG, C_POINTER, C_POINTER));

  static final MethodHandle JobProcessor_Process_Return$MH =
      downcall("JobProcessor_Process_Return", FunctionDescriptor.ofVoid(C_LONG_LONG, C_POINTER, C_SIZE_T, C_POINTER));

  static final MethodHandle JobQueue_Create$MH =
      downcall("JobQueue_Create", FunctionDescriptor.of(C_POINTER, C_POINTER, C_POINTER));

  static final MethodHandle JobQueue_Push_Start$MH =
      downcall("JobQueue_Push_Start", FunctionDescriptor.of(C_LONG_LONG, C_POINTER, C_SIZE_T, C_LONG_LONG));

  static final MethodHandle JobQueue_Push_Await$MH =
      downcall("JobQueue_Push_Await", FunctionDescriptor.of(C_POINTER, C_LONG_LONG, C_POINTER));

  static final MethodHandle JobQueue_Get$MH =
      downcall("JobQueue_Get", FunctionDescriptor.of(C_POINTER, C_POINTER, C_POINTER));

  static final MethodHandle JobProcessors_Register$MH =
      downcall("JobProcessors_Register", FunctionDescriptor.of(C_SHORT, C_POINTER, C_LONG_LONG));

  private static final MethodHandle InitLibrary$MH =
      downcall("InitLibrary", FunctionDescriptor.ofVoid());

  // Last, and after the handle it calls: a static block may not read a field declared
  // below it, and every layout and handle above has to exist before the library runs.
  static {
    try {
      InitLibrary$MH.invokeExact();
    } catch (Throwable t) {
      throw rethrow(t);
    }
  }
}
