// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs.api;

/**
 * A {@code @throws} method whose implementation returned an error, or a failure of the
 * boundary itself.
 *
 * <p>Unchecked, so that a signature stays readable: the Go side declares the error in its
 * return tuple rather than in the method's type, and there is nothing in the definitions
 * file that could name a checked exception.
 *
 * <p>Generated — do not edit.
 */
public class FfiException extends RuntimeException {

  private static final long serialVersionUID = 1L;

  public FfiException(String message) {
    super(message);
  }

  public FfiException(Throwable cause) {
    super(cause);
  }
}
