// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs.api;

/**
 * A {@code @listener}: implemented by you, called by the library.
 *
 * <p>A method returning {@code void} is <b>fire-and-forget</b> — the library posts the
 * invocation and carries on without waiting, so nothing you do there can be observed by the
 * caller, and taking a long time applies back-pressure rather than blocking it.
 *
 * <p>{@link #process} <b>answers back</b>: the
 * library waits for the value or the exception, so the goroutine that called is parked until
 * you return. Whatever you throw reaches the Go implementation as its error. Take as long as
 * you need — but do not wait on something that can only happen once this same listener has
 * been called again, which is the one shape that cannot resolve.
 *
 * <p>Calls arrive on a daemon thread. Fire-and-forget ones are delivered in the order the
 * library made them, on {@code genffi-upcall}; a method that answers runs on
 * {@code genffi-answer} instead, so that a body which calls back into the library does not
 * block the thread that has to deliver the answer. Calling into the library from here is
 * therefore safe, and is the reason for the second pool.
 *
 * <p>An exception thrown by a fire-and-forget method is caught and reported to
 * {@code System.err}; it cannot reach the library.
 *
 * <pre>{@code
 * try (var registration = JobProcessor.register(myImplementation)) {
 *   // pass registration wherever the api declares a JobProcessor parameter
 * }
 * }</pre>
 *
 * <p>Generated — do not edit.
 */
public interface JobProcessor {

  de.ii.xtralink.jobs.JobResult process(de.ii.xtralink.jobs.Job job) throws Exception;

  /**
   * Registers {@code implementation} with the library and returns the token holding its id.
   * Close the token when you are done; until you do, the library keeps delivering to it.
   */
  static Registration register(JobProcessor implementation) {
    return new Registration(Ffi.register$(implementation));
  }

  /** A live registration. Pass it where a {@code JobProcessor} parameter is declared. */
  final class Registration implements AutoCloseable {

    private final long id;
    private boolean closed;

    Registration(long id) {
      this.id = id;
    }

    long id() {
      return id;
    }

    /**
     * Stops delivery and releases the id. Idempotent.
     *
     * <p>Invocations the library has already posted may still arrive; ones it posts
     * afterwards are dropped. That is deliberate — a registration closing while the
     * implementation is mid-emit is an ordinary race, and there is nobody left to deliver
     * to.
     */
    @Override
    public void close() {
      if (closed) {
        return;
      }

      closed = true;
      Ffi.unregister$(id);
    }
  }
}
