// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs.api;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

/**
 * A {@code @singleton}: one instance for the process, constructed by {@code InitLibrary}
 * when {@code Ffi} is first touched. Nothing to hold, hence static methods and no
 * constructor.
 *
 * <p>Generated — do not edit.
 */
public final class JobProcessors {

  private JobProcessors() {}

  public static boolean register(String jobType, JobProcessor.Registration processor) {
    try (Arena arena = Arena.ofConfined()) {
      short ret$ = (short) Ffi.JobProcessors_Register$MH.invokeExact(Ffi.str(arena, jobType), processor.id());

      return ret$ == 1;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }
}
