// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs.api;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

/**
 * A {@code @singleton}: one instance for the process, constructed by {@code InitLibrary}
 * when {@code Ffi} is first touched. Nothing to hold, hence static methods and no
 * constructor.
 *
 * <p>Generated — do not edit.
 */
public final class JobQueue {

  private JobQueue() {}

  public static de.ii.xtralink.jobs.Job create(String jobType) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment clen$ = arena.allocate(Ffi.C_SIZE_T);
      MemorySegment ret$ = (MemorySegment) Ffi.JobQueue_Create$MH.invokeExact(Ffi.str(arena, jobType), clen$);
      long len$ = clen$.get(Ffi.C_SIZE_T, 0);

      de.ii.xtralink.jobs.Job out$ = Ffi.json$read(ret$, len$, de.ii.xtralink.jobs.Job.class);
      Ffi.freeBytes(ret$);

      return out$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  public static java.util.concurrent.CompletableFuture<de.ii.xtralink.jobs.Job> push(de.ii.xtralink.jobs.Job cfg, JobListener.Registration onProgress) {
    final long future$;

    try (Arena arena = Arena.ofConfined()) {
      byte[] cfg$json = Ffi.json$write(cfg);
      long ret$ = (long) Ffi.JobQueue_Push_Start$MH.invokeExact(Ffi.bytes(arena, cfg$json), cfg$json == null ? 0L : (long) cfg$json.length, onProgress.id());

      future$ = ret$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }

    return Ffi.pending$(future$, () -> await$push(future$));
  }

  private static de.ii.xtralink.jobs.Job await$push(long future$) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment clen$ = arena.allocate(Ffi.C_SIZE_T);
      MemorySegment ret$ = (MemorySegment) Ffi.JobQueue_Push_Await$MH.invokeExact(future$, clen$);
      long len$ = clen$.get(Ffi.C_SIZE_T, 0);

      de.ii.xtralink.jobs.Job out$ = Ffi.json$read(ret$, len$, de.ii.xtralink.jobs.Job.class);
      Ffi.freeBytes(ret$);

      return out$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }

  /**
   * Registers {@code onProgress} and releases it again when
   * the returned future completes.
   *
   * <p>Available because the method is declared {@code @scoped}, which asserts that it does
   * not retain the listener beyond that point. Use the {@code Registration}
   * overload for a listener that has to outlive it.
   */
  public static java.util.concurrent.CompletableFuture<de.ii.xtralink.jobs.Job> push(de.ii.xtralink.jobs.Job cfg, JobListener onProgress) {
    JobListener.Registration onProgress$reg = JobListener.register(onProgress);

    return push(cfg, onProgress$reg).whenComplete((result$, error$) -> { onProgress$reg.close(); });
  }

  public static de.ii.xtralink.jobs.Job get(String id) {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment clen$ = arena.allocate(Ffi.C_SIZE_T);
      MemorySegment ret$ = (MemorySegment) Ffi.JobQueue_Get$MH.invokeExact(Ffi.str(arena, id), clen$);
      long len$ = clen$.get(Ffi.C_SIZE_T, 0);

      de.ii.xtralink.jobs.Job out$ = Ffi.json$read(ret$, len$, de.ii.xtralink.jobs.Job.class);
      Ffi.freeBytes(ret$);

      return out$;
    } catch (Throwable t) {
      throw Ffi.rethrow(t);
    }
  }
}
