// Code generated by genffi. DO NOT EDIT.

/**
 * The FFM binding to the {@code xtralink} shared library, generated from the same
 * {@code GenApi} as the CGo wrapper it calls.
 *
 * <h2>1. Build the library</h2>
 *
 * The Go side is generated too, along with the {@code Makefile} that links it. From the
 * generated {@code <cgo.pkg>/main} directory:
 *
 * <pre>{@code
 * make shared              # -> libxtralink.dylib, libxtralink.so or xtralink.dll
 * make shared OUT=../..    # somewhere else
 * }</pre>
 *
 * <p>The name is load-bearing: {@code Ffi} calls
 * {@code System.loadLibrary("xtralink")}, which resolves exactly what the Makefile
 * produces on each platform. Renaming the file breaks the lookup.
 *
 * <h2>2. Compile</h2>
 *
 * <pre>{@code
 * javac --release 22 -d classes de/ii/xtralink/jobs/api/*.java
 * }</pre>
 *
 * <p>22 is a floor rather than a preference — {@code java.lang.foreign} left
 * preview there, so nothing older compiles {@code Ffi} at all. {@code GenModel} records, if
 * you generate those too, still compile on 17.
 *
 * <p><b>Jackson is required on the class path</b>, at compile time and at run time. The
 * signatures here carry {@code GenModel} types, which cross the boundary as JSON, and
 * {@code Ffi} marshals them with {@code ObjectMapper}. A binding whose signatures name no
 * model type needs nothing but the JDK.
 *
 * <h2>3. Run</h2>
 *
 * <pre>{@code
 * java --enable-native-access=ALL-UNNAMED \
 *      -Djava.library.path=<the directory holding the library> \
 *      -cp classes <your main class>
 * }</pre>
 *
 * <p>Both flags earn their place. Without {@code --enable-native-access} the JVM warns on
 * every restricted call today and is documented to refuse them in a future release; name your
 * own module instead of {@code ALL-UNNAMED} if you have one. Without the library path
 * {@code System.loadLibrary} has nowhere to look.
 *
 * <p>To point at one exact file instead of a search path — a test fixture, or a build that
 * puts the library somewhere unusual — set
 * {@code -Dgenffi.library.xtralink=/path/to/libxtralink.so} and {@code Ffi} loads that and
 * nothing else.
 *
 * <p>Generated — do not edit. See {@code docs/guide/java-binding.md} for the memory
 * contract and what each class here is for.
 */
package de.ii.xtralink.jobs.api;
