// Code generated by genffi. DO NOT EDIT.

package api

import model "github.com/ldproxy/xtralink/model"






type JobListener interface {
  OnProgress(job model.Job) 
}


type JobProcessor interface {
  Process(job model.Job) (model.JobResult, error)
}


type JobQueue interface {
  Create(jobType string) model.Job
  Push(cfg model.Job, onProgress JobListener) model.Job
  Get(id string) model.Job
}


type JobProcessors interface {
  Register(jobType string, processor JobProcessor) bool
}

      