// Code generated by genffi. DO NOT EDIT.
//
// Implementation skeletons: every method panics. This file is rewritten on every
// run, so implement the api package in a file of your own and keep this one as the
// list of what is still missing.

package impl
		
import api "github.com/ldproxy/xtralink/ffi/api"
import model "github.com/ldproxy/xtralink/model"


	//=== JobQueue ===

type JobQueue struct {
}

func NewJobQueue() *JobQueue {
	return &JobQueue{}
}
	

func (s *JobQueue) Create(jobType string) model.Job {
    panic("not implemented yet")
}
	


func (s *JobQueue) Push(cfg model.Job, onProgress api.JobListener) model.Job {
    panic("not implemented yet")
}
	


func (s *JobQueue) Get(id string) model.Job {
    panic("not implemented yet")
}
	
	

	//=== JobProcessors ===

type JobProcessors struct {
}

func NewJobProcessors() *JobProcessors {
	return &JobProcessors{}
}
	

func (s *JobProcessors) Register(jobType string, processor api.JobProcessor) bool {
    panic("not implemented yet")
}
	
	

    