// Code generated by genffi. DO NOT EDIT.
//
// Implementation skeletons: every method panics. This file is rewritten on every
// run, so implement the api package in a file of your own and keep this one as the
// list of what is still missing.

package impl
