// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;
  
public interface BaseJob {
  
String id();
  
String kind();
  
Long createdAt();
  
Long startedAt();
  
Long updatedAt();
  
Long finishedAt();
  
Integer priority();
  
JobProgress progress();
  
Identifiers.Status status();
  
java.util.List<String> errors();
  
java.util.Map<String, Object> context();
  
}
  