// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public interface Identifiers {
    

  enum Status { ACCEPTED, RUNNING, SUCCESSFUL, FAILED, DISMISSED };
  enum ProgressOperation { ADD, SUBTRACT };
  enum Result { SUCCESS, FAILURE, RETRY, ONHOLD };
  enum Queue { LOCAL, REDIS };
}
