// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record InitProgress(
    Integer total,
    java.util.Map<String, Object> details
  ) {

public InitProgress(
  Integer total,
  java.util.Map<String, Object> details
) {
  this.total = total;
  this.details = details;
}
  
}

