// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record Job(
    String id,
    String kind,
    Long createdAt,
    Long startedAt,
    Long updatedAt,
    Long finishedAt,
    Integer priority,
    JobProgress progress,
    Identifiers.Status status,
    java.util.List<String> errors,
    java.util.Map<String, Object> context,
    String label,
    String description,
    java.util.Map<String, Object> inputs,
    java.util.Map<String, Object> outputs,
    java.util.Optional<PartialJob> setup,
    java.util.Optional<PartialJob> cleanup,
    java.util.List<Job> followUps,
    java.util.Optional<JobSequence> sequence
  ) implements BaseJob {

public Job(
  String id,
  String kind,
  Long createdAt,
  Long startedAt,
  Long updatedAt,
  Long finishedAt,
  Integer priority,
  JobProgress progress,
  Identifiers.Status status,
  java.util.List<String> errors,
  java.util.Map<String, Object> context,
  String label,
  String description,
  java.util.Map<String, Object> inputs,
  java.util.Map<String, Object> outputs,
  java.util.Optional<PartialJob> setup,
  java.util.Optional<PartialJob> cleanup,
  java.util.List<Job> followUps,
  java.util.Optional<JobSequence> sequence
) {
  this.id = id;
  this.kind = kind;
  this.createdAt = createdAt;
  this.startedAt = startedAt;
  this.updatedAt = updatedAt;
  this.finishedAt = finishedAt;
  this.priority = priority;
  this.progress = progress;
  this.status = status;
  this.errors = errors;
  this.context = context;
  this.label = label;
  this.description = description;
  this.inputs = inputs;
  this.outputs = outputs;
  this.setup = setup;
  this.cleanup = cleanup;
  this.followUps = followUps;
  this.sequence = sequence;
}
  
}

