// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record JobConfiguration(
    String kind,
    Integer priority,
    String label,
    String description,
    java.util.Map<String, Object> inputs,
    java.util.Map<String, Object> context,
    JobProgress progress,
    Boolean setup,
    Boolean cleanup,
    java.util.List<JobConfiguration> followUps,
    java.util.Optional<Integer> ttlSeconds
  ) {

public JobConfiguration(
  String kind,
  Integer priority,
  String label,
  String description,
  java.util.Map<String, Object> inputs,
  java.util.Map<String, Object> context,
  JobProgress progress,
  Boolean setup,
  Boolean cleanup,
  java.util.List<JobConfiguration> followUps,
  java.util.Optional<Integer> ttlSeconds
) {
  this.kind = kind;
  this.priority = priority;
  this.label = label;
  this.description = description;
  this.inputs = inputs;
  this.context = context;
  this.progress = progress;
  this.setup = setup;
  this.cleanup = cleanup;
  this.followUps = followUps;
  this.ttlSeconds = ttlSeconds;
}
  
}

