// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record JobProgress(
    Integer current,
    Integer total,
    Integer percent,
    java.util.Map<String, Object> details
  ) {

public JobProgress(
  Integer current,
  Integer total,
  Integer percent,
  java.util.Map<String, Object> details
) {
  this.current = current;
  this.total = total;
  this.percent = percent;
  this.details = details;
}
  
}

