// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record JobResult(
    String message,
    Identifiers.Status status,
    java.util.List<String> errors
  ) {

public JobResult(
  String message,
  Identifiers.Status status,
  java.util.List<String> errors
) {
  this.message = message;
  this.status = status;
  this.errors = errors;
}
  
}

