// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record JobResult(
    Identifiers.Result status,
    java.util.List<String> messages
  ) {

public JobResult(
  Identifiers.Result status,
  java.util.List<String> messages
) {
  this.status = status;
  this.messages = messages;
}
  
}

