// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record JobSequence(
    Integer current,
    Integer remaining
  ) {

public JobSequence(
  Integer current,
  Integer remaining
) {
  this.current = current;
  this.remaining = remaining;
}
  
}

