// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record OutputValue(
    Object value,
    String href,
    String kind
  ) {

public OutputValue(
  Object value,
  String href,
  String kind
) {
  this.value = value;
  this.href = href;
  this.kind = kind;
}
  
}

