// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record PartialJobConfiguration(
    String kind,
    Integer priority,
    String partOf,
    JobProgress progress,
    java.util.List<ProgressUpdate> progressUpdates,
    java.util.Optional<Integer> sequence,
    java.util.Map<String, Object> context
  ) {

public PartialJobConfiguration(
  String kind,
  Integer priority,
  String partOf,
  JobProgress progress,
  java.util.List<ProgressUpdate> progressUpdates,
  java.util.Optional<Integer> sequence,
  java.util.Map<String, Object> context
) {
  this.kind = kind;
  this.priority = priority;
  this.partOf = partOf;
  this.progress = progress;
  this.progressUpdates = progressUpdates;
  this.sequence = sequence;
  this.context = context;
}
  
}

