// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record PartialJob(
    String id,
    String kind,
    Long createdAt,
    Long startedAt,
    Long updatedAt,
    Long finishedAt,
    Integer priority,
    JobProgress progress,
    Identifiers.Status status,
    java.util.List<String> errors,
    java.util.Map<String, Object> context,
    String partOf,
    String executor,
    Boolean onHold,
    java.util.List<ProgressUpdate> progressUpdates,
    java.util.Optional<Integer> sequence
  ) implements BaseJob {

public PartialJob(
  String id,
  String kind,
  Long createdAt,
  Long startedAt,
  Long updatedAt,
  Long finishedAt,
  Integer priority,
  JobProgress progress,
  Identifiers.Status status,
  java.util.List<String> errors,
  java.util.Map<String, Object> context,
  String partOf,
  String executor,
  Boolean onHold,
  java.util.List<ProgressUpdate> progressUpdates,
  java.util.Optional<Integer> sequence
) {
  this.id = id;
  this.kind = kind;
  this.createdAt = createdAt;
  this.startedAt = startedAt;
  this.updatedAt = updatedAt;
  this.finishedAt = finishedAt;
  this.priority = priority;
  this.progress = progress;
  this.status = status;
  this.errors = errors;
  this.context = context;
  this.partOf = partOf;
  this.executor = executor;
  this.onHold = onHold;
  this.progressUpdates = progressUpdates;
  this.sequence = sequence;
}
  
}

