// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record ProgressUpdate(
    String path,
    Identifiers.ProgressOperation operation
  ) {

public ProgressUpdate(
  String path,
  Identifiers.ProgressOperation operation
) {
  this.path = path;
  this.operation = operation;
}
  
}

