// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record QueueConfiguration(
    Integer concurrency,
    String executor,
    Identifiers.Queue queue,
    java.util.Optional<String> cluster,
    java.util.List<String> redis
  ) {

public QueueConfiguration(
  Integer concurrency,
  String executor,
  Identifiers.Queue queue,
  java.util.Optional<String> cluster,
  java.util.List<String> redis
) {
  this.concurrency = concurrency;
  this.executor = executor;
  this.queue = queue;
  this.cluster = cluster;
  this.redis = redis;
}
  
}

