// Code generated by genffi. DO NOT EDIT.

package de.ii.xtralink.jobs;

public record SetOutputs(
    java.util.Map<String, Object> outputs
  ) {

public SetOutputs(
  java.util.Map<String, Object> outputs
) {
  this.outputs = outputs;
}
  
}

